export const simulations = [
  {
    id: "1",
    company: "AMD",
    role: "PCB Design for High-Power Systems",
    industry: "Semiconductor",
    skills: ["Hardware", "PCB", "Power"],
    duration: "12 Hours",
    difficulty: "Intermediate",
    description: "Design and optimize high-power PCB layouts for advanced computing systems. Apply signal integrity principles and thermal management techniques.",
    badge: "Advanced PCB Specialist",
    fastTrack: true,
    logo: "A",
    color: "bg-red-100 text-red-600",
  },
  {
    id: "2",
    company: "Intel",
    role: "ASIC Verification with SystemVerilog",
    industry: "Semiconductor",
    skills: ["ASIC", "Verification", "VLSI"],
    duration: "20 Hours",
    difficulty: "Expert",
    description: "Verify ASIC designs using SystemVerilog testbenches. Debug timing violations and ensure functional correctness.",
    badge: "ASIC Verification Engineer",
    fastTrack: true,
    logo: "I",
    color: "bg-blue-100 text-blue-600",
  },
  {
    id: "3",
    company: "NVIDIA",
    role: "Embedded Systems Firmware Dev",
    industry: "Advanced Electronics",
    skills: ["C++", "RTOS", "Embedded"],
    duration: "15 Hours",
    difficulty: "Intermediate",
    description: "Develop firmware for embedded GPU control systems. Implement RTOS scheduling and hardware abstraction layers.",
    badge: "Embedded Firmware Developer",
    fastTrack: false,
    logo: "N",
    color: "bg-green-100 text-green-600",
  },
  {
    id: "4",
    company: "TSMC",
    role: "Introduction to CMOS Fabrication",
    industry: "Semiconductor",
    skills: ["Next-Gen Manufacturing", "Fab", "Cleanroom"],
    duration: "8 Hours",
    difficulty: "Beginner",
    description: "Learn the fundamentals of CMOS fabrication processes including lithography, etching, and deposition in a simulated cleanroom environment.",
    badge: "CMOS Fabrication Foundations",
    fastTrack: false,
    logo: "T",
    color: "bg-purple-100 text-purple-600",
  },
  {
    id: "5",
    company: "Texas Instruments",
    role: "Analog IC Design: Op-Amp Focus",
    industry: "Semiconductor",
    skills: ["Analog", "IC Design", "Simulation"],
    duration: "25 Hours",
    difficulty: "Expert",
    description: "Design operational amplifiers from scratch. Optimize gain, bandwidth, and power consumption using industry-standard EDA tools.",
    badge: "Analog IC Designer",
    fastTrack: true,
    logo: "TI",
    color: "bg-orange-100 text-orange-600",
  },
  {
    id: "6",
    company: "Xilinx",
    role: "FPGA Prototyping for AI Engines",
    industry: "Advanced Electronics",
    skills: ["FPGA", "AI", "Digital"],
    duration: "18 Hours",
    difficulty: "Intermediate",
    description: "Prototype AI inference engines on FPGA platforms. Optimize for latency and throughput using high-level synthesis.",
    badge: "FPGA AI Specialist",
    fastTrack: true,
    logo: "X",
    color: "bg-teal-100 text-teal-600",
  },
];

export const skillTags = [
  "Hardware", "PCB", "Power", "ASIC", "Verification", "VLSI",
  "C++", "RTOS", "Embedded", "Next-Gen Manufacturing", "Fab", "Cleanroom",
  "Analog", "IC Design", "FPGA", "AI", "Digital",
];

export const studentProgress = {
  completedSimulations: 4,
  totalSimulations: 6,
  interviews: 2,
  credentials: 3,
  skillsPerformance: "A+",
  badges: [
    { name: "Wafer Fabrication Associate", company: "TSMC", date: "2024", verified: true, skills: ["Cleanroom", "EPI", "QA"] },
    { name: "NAND Flash Architect", company: "Western Digital", date: "Feb 28, 2024", verified: true, skills: ["SSD", "Logic Design"] },
    { name: "IC Packaging Specialist", company: "Amkor Technology", date: "Jan 15, 2024", verified: true, skills: ["Wirebonding", "SMT"] },
  ],
  competencyMap: [
    { name: "Semiconductor Quality Assurance", level: "Advanced", progress: 85 },
    { name: "PCB Layout & Design", level: "Intermediate", progress: 62 },
    { name: "Analog Electronics Testing", level: "Beginner", progress: 45 },
    { name: "VLSI Fundamentals", level: "Expert", progress: 92 },
  ],
  timeline: [
    { time: "2 hours ago", title: "Interview Unlocked", desc: "Met prerequisites for Junior Test Engineer at Hana Microelectronics." },
    { time: "Yesterday", title: "Credential Verified", desc: "Western Digital confirmed your NAND Flash simulation score." },
    { time: "3 days ago", title: "Task Submitted", desc: "Uploaded project for IC Thermal Analysis simulation." },
    { time: "5 days ago", title: "Enrolled in Simulation", desc: "Started 'Advanced PCB Routing for Mobile SoCs'." },
  ],
  opportunities: [
    { role: "Junior IC Design Engineer", company: "Sony Thailand", status: "UNLOCKED" },
    { role: "PCB Design Intern", company: "Hana Micro", status: "INVITED" },
    { role: "Analog Circuits Tech", company: "Delta Electronics", status: "SHORTLISTED" },
  ],
};

export const adminKPIs = {
  activeJobOpenings: 1482,
  jobOpeningsChange: 14.2,
  totalPipeline: 8240,
  pipelineChange: 8.1,
  skillGapSeverity: "Critical",
  skillGapChange: -2.4,
  avgStartingSalary: "฿32.5k",
  salaryChange: 12.0,
};

export const skillGapData = [
  { skill: "Semiconductor QA", demand: 85, supply: 42 },
  { skill: "PCB Process", demand: 72, supply: 55 },
  { skill: "Materials Science", demand: 68, supply: 38 },
  { skill: "Electronics Testing", demand: 90, supply: 60 },
  { skill: "Adv. Manufacturing", demand: 78, supply: 45 },
  { skill: "Data Analysis", demand: 65, supply: 70 },
];

export const talentForecastData = [
  { month: "Jul 24", demand: 3200, supply: 2800 },
  { month: "Sep 24", demand: 3800, supply: 3100 },
  { month: "Nov 24", demand: 4200, supply: 3400 },
  { month: "Jan 25", demand: 5000, supply: 3800 },
  { month: "Mar 25", demand: 5800, supply: 4200 },
  { month: "May 25", demand: 6800, supply: 4800 },
  { month: "Jul 25", demand: 7800, supply: 5400 },
];

export const regionalDemand = [
  { region: "Bangkok / Vicinity", change: "+12%", pct: 85 },
  { region: "Chonburi (EEC)", change: "+24%", pct: 95 },
  { region: "Rayong (Industrial)", change: "+18%", pct: 75 },
  { region: "Chiang Mai (Tech Hub)", change: "+5%", pct: 40 },
  { region: "Ayutthaya (Manuf.)", change: "+8%", pct: 55 },
];

export const recruiterData = {
  activeSimulations: 8,
  simChange: "+2 this month",
  candidatesInPipeline: 1842,
  candidateLabel: "Total enrollments",
  avgTimeToShortlist: "4.2d",
  timeLabel: "Last 30 days",
  funnelData: [
    { stage: "Enrolled", value: 500 },
    { stage: "Task 1 Clear", value: 340 },
    { stage: "Task 2 Clear", value: 280 },
    { stage: "Qualified", value: 180 },
    { stage: "Shortlisted", value: 45 },
  ],
  submissions: [
    { name: "Arisa Kittisiri", university: "Chulalongkorn University", simulation: "Wafer Test Engineer", score: 92, status: "Awaiting Review" },
    { name: "Tanawat P.", university: "KMUTT", simulation: "PCB Layout Intern", score: 85, status: "Qualified" },
    { name: "Sarai Nim", university: "Mahidol University", simulation: "QA Specialist", score: 78, status: "In Progress" },
    { name: "Wichit S.", university: "Kasetsart University", simulation: "Wafer Test Engineer", score: 94, status: "Shortlisted" },
    { name: "Ploy Jinda", university: "Chulalongkorn University", simulation: "IC Design Junior", score: 81, status: "Qualified" },
  ],
  stats: { dropOffRate: "32%", taskClearRate: "68.4%", avgTestScore: "82.1", hiringIntent: "High" },
};
